IMAGE_INSTALL_append = " peekpoke"
IMAGE_INSTALL_append = " gpio-demo"
IMAGE_INSTALL_append = " executable"
IMAGE_INSTALL_append = " libvrcDemo"
IMAGE_INSTALL_append = " samplevrc"
IMAGE_INSTALL_append = " supportDocs"
